var XTypes={Tooltip:0,Window:1,Message:2};var Xirt=new Class({initialize:function(){this._analyse();this._statistics();this._notifications();if((Browser.version<8&&Browser.ie)||(Browser.firefox&&Browser.version<4)){Asset.javascript("js/xupdate.js");
}},_analyse:function(){$$("a[rel*=external]").each(function(a){a.setProperty("target","_blank");a.addClass("external");});Array.combine($$("a[rel*=pdf]"),$$("a[href$=.pdf]")).each(function(a){a.addEvent("click",function(b){new PDF(b,this);
});});},_notifications:function(){this.roar=new Roar({position:"upperRight"});},_statistics:function(){var a=$("xStatsBox");if(typeOf(a)=="element"){a.addEvent("click",function(){this.fade();
});}},showWindow:function(b,a){return new Window(b,a);},showMessage:function(a){new Message(a);},showNotice:function(a){Xirt.roar.alert(XLang.messages.system,a);
},showError:function(){Xirt.roar.alert(XLang.messages.system,XLang.errors.communication);},showTooltip:function(b,a){new Tooltip(b,a);},hideTooltips:function(){Array.each(XRegister.toArray(XTypes.Tooltip),function(a){a.hide();
});},hideAllTooltips:function(){Xirt.showNotify("Deprecated use of Xirt.hideAllTooltips();");this.hideTooltips();},populateForm:function(a,b){Object.every(b,function(e,d){var c=a.getElement("[name=x_"+d+"]");
if(typeOf(c)=="element"){return c.set("value",e);}var c=a.getElement("[name="+d+"]");if(typeOf(c)=="element"){return c.set("value",e);}return true;},this);
}});var XRegister=new Class({_storage:[],add:function(a){this._storage[this._storage.length]=a;},remove:function(a){this._storage.erase(a);},isRegistered:function(b){var a=Array.filter(this._storage,function(c){return(c.id==b);
});return a.length?a[0]:null;},toArray:function(a){return Array.filter(this._storage,function(b){return(b.type==a);},this);}});window.addEvent("domready",function(){Xirt=new Xirt();
XRegister=new XRegister();});var Window=new Class({Implements:[Options,Events],type:XTypes.Window,options:{width:750},initialize:function(b,a){this.fog=new Fog();
this._create(a);this._register();this.set(b);},set:function(b){if(typeof(b)!="string"){this.content.grab(b);}else{var a=new Element("div",{"class":"box-buttons"});
a.grab(new Element("button",{"class":"close xButton",text:XLang.misc.close}));this.content.set("html",b);this.element.grab(a);}Array.each(this.element.getElements(".close"),function(c){c.addEvent("click",this.hide.bind(this));
},this);},_register:function(){XRegister.add(this);window.addEvent("resize",this._reposition.bind(this));if(Browser.ie){window.addEvent("scroll",this._reposition.bind(this));
}},_position:function(){this.element.position({relativeTo:$(document.body),ignoreScroll:true,relFixedPosition:Browser.ie?true:false,position:"centerTop",edge:"centerTop"});
this.element.setStyle("position","fixed");},show:function(){this.fog.show();Xirt.hideTooltips();this.element.reveal();},hide:function(){this.element.dissolve();
Xirt.hideTooltips();this.fog.hide();},removeWindow:function(a){Xirt.showNotify("Deprecated use of Window.removeWindow()");a=$(a);if(!a||!a.isVisible()){return false;
}Xirt.window.dispose();},_reposition:function(){if(this.element.isVisible()){this._position();}},_create:function(a){this.element=new Element("div",{"class":"xirt-window"}).setStyles({width:a?a:750+"px"}).inject(document.body).hide();
this.content=new Element("div",{"class":"xirt-content"}).setStyles({"max-height":Math.max(window.getSize().y-75,250)+"px"}).inject(this.element);this._position();
}});var Tooltip=new Class({Implements:[Options],type:XTypes.Tooltip,initialize:function(c,a,b){this.setOptions(b);this._create(a);this._attach(c);this._register();
this.show();},_create:function(a){this.element=new Element("div",{"class":"xirt-tooltip"}).fade("out");this.set(a);this.element.inject($(document.body));
},set:function(a){new Element("p",{text:a}).inject(this.element.empty());},_attach:function(a){a.tooltip=this;this.container=a;this.element.position({relativeTo:a,position:"centerRight",edge:"centerLeft",offset:{x:+4,y:a.getScroll().y}});
},_register:function(){XRegister.add(this);},show:function(a){if(a&&a.trim()){this.set(a);}return this.element.fade("in");},hide:function(){return this.element.fade("out");
},update:function(a){this._attach(this.container);this.show(a);}});var Message=new Class({Implements:[Options],type:XTypes.Message,initialize:function(a,b){this.setOptions(b);
this._create(a);this._position();this._register();this.show();},_create:function(a){this.element=new Element("div",{"class":"xirt-alert",text:a}).inject(document.body);
var b=new Element("div",{"class":"box-buttons"}).inject(this.element);b.grab(new Element("button",{text:XLang.misc.close}).addEvent("click",this.hide.bind(this)));
this.element.grab(b);},_position:function(a){this.element.position({relativeTo:$("body"),position:"center",edge:"bottom",offset:{x:0,y:-100}}).fade("hide");
},_register:function(){XRegister.add(this);},show:function(){return this.element.fade("in");},hide:function(){XRegister.remove(this);return this.element.fade("out");
}});var Fog=new Class({Implements:Options,element:null,options:{opacity:0.5},initialize:function(a){this.setOptions(a);if(!(this.element=$("xBG"))||!this.element){this._create();
}},_create:function(a){this.element=new Element("div",{"class":"xirt-overlay",id:"xBG"}).inject(document.body);},_resize:function(){this.element.setStyles({width:screen.width+"px",height:screen.height+"px"});
},show:function(){this.hide(1);this._resize();return this.element.fade(this.options.opacity);},hide:function(a){return this.element.fade(a?"hide":"out");
}});var PDF=new Class({_reader:"http://get.adobe.com/reader/",_path:null,initialize:function(b,a){if(!Cookie.read("pdf")){this._path=a.get("href");Cookie.write("pdf","1");
b.stop();this._create();this.show();}},_create:function(){this.container=new Element("div",{"class":"xPDF"});this.container.grab(new Element("h1",{text:XLang.reader.header}));
this.container.grab(new Element("p",{text:XLang.reader.introduction}));var b=new Element("div",{"class":"box-download"});b.grab(new Element("button",{type:"button",text:XLang.reader.download,"class":"xPDF"}).addEvent("click",this._download.bind(this)));
this.container.grab(b);this.container.grab(new Element("p",{text:XLang.reader.alternative}));var a=new Element("div",{"class":"box-buttons"});a.grab(new Element("button",{type:"button",text:XLang.reader["continue"]}).addEvent("click",this._continue.bind(this)));
a.grab(new Element("button",{type:"button",text:XLang.reader.cancel,"class":"close"}));this.container.grab(a);this.window=new Window(this.container,500);
},_continue:function(){window.open(this._path);this.hide();},_download:function(){window.open(this._reader);},show:function(){this.window.show();},hide:function(){this.window.hide();
}});Request.Form=new Class({Extends:Request,initialize:function(b,a){a=a?a:{};a.data=b;this.parent(a);}});